version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/app
    ports:
    - 80:8000
    command: php -S 0.0.0.0:8000 -t /app

  nginx:
    image: nginx:latest

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    container_name: sqlserver
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql






